### PR TITLE
Massive application filesize reduction, and new LEAF Planet Blue color

### PR DESCRIPTION
**Pull request by dalathegreat**
- Compressed all main car images, for a filesize reduction of 14,6MB -> 4,75MB. This should cut the application filesize quite nicely (it's currently 24MB)
- Added one more color option for LEAF, 'Planet Blue'

### CODE REVIEW

**Comment by dalathegreat** [comment]
Second time is the charm :D

**Comment by dexterbg** [comment]
Daniel, the App crashes when selecting the "planet blue" Leaf. Reason is most probably the missing map icon for that color. Can you provide that for the fix release today? If not I'll copy the other blue Leaf icon.

**Comment by dexterbg** [comment]
Btw: are you subscribed to the developer list? Crash report came in there.

**Comment by dexterbg** [comment]
Verified: it's the missing map image. As users can only recover by erasing the App data, the fix is urgent.

**Comment by dexterbg** [comment]
Just saw the Leaf map icons are just scaled down ol images, so I'll fix it myself.

**Comment by dalathegreat** [comment]
Sorry I missed this crisis completely, good that you got identified and fixed it already! How do I sub to the dev list?

**Comment by dexterbg** [comment]
http://lists.openvehicles.com/mailman/listinfo/ovmsdev

**Comment by glynhudson** [comment]
@dalethegreat what did you use to perform the image compression? I'm in the process of adding the graphics for the MG ZS EV but can't seem to achieve the same low file size

**Comment by dalathegreat** [comment]
@glynhudson I think I used this online tool https://www.img2go.com/compress-image

**Comment by glynhudson** [comment]
> @glynhudson I think I used this online tool https://www.img2go.com/compress-image

Thanks, that worked well. 300kb > 80kb without any noticeable loss of quality. Very impressive :+1:

**Pull request merged**
