### PR TITLE
Charging Animation, Updated Battery and Car site for Smart EQ (SQ)

### PR DESCRIPTION
**Pull request by zorgms**
Added a Charging animation inspired by request #151 

for Smart EQ:
Battery site:
- cabin and ambient temperature added
- A/C button added, incl. A/C starting option

Car site:
- cabin and ambient temperature listed left row
- Energy, SoC an SoH added to the bottum row
- fixed wrong TMPS tyre side, right left were swapped

At this time need a Dirty OVMS Firmware by @Dimitrie78 and a JS Script to show all information.

image

smart_charging

### CODE REVIEW

**Comment by zorgms** [comment]
Screenshot_20240915-174211

**Comment by dexterbg** [comment]
ZorG, if this is work in progress, maybe set this PR to "draft" until ready for merging?

**Comment by zorgms** [comment]
It's ready for merging. No more errors were reported.

**Comment by zorgms** [comment]
still WIP, new fnc and update for Booster menu

**Comment by zorgms** [comment]
At this point I'm done. Maybe...

Implented:

1. Plugin menu, can activated at options menu and showed at homelink menu. The plugins works on various cars.
2. Firmware menu, can activated at options menu and showed at homelink menu.
3. scheduled heater control. You can set starting time at A/C menu (only when scheduled_booster plugin installed)
4. added Smart EQ 42/44 images

**Comment by zorgms** [comment]
image

**Comment by dexterbg** [comment]
ZorG,

as this seems to have settled a bit, I've taken a look at the current state. Lots of nice additions.

I cannot test the Smart EQ specific additions. Here are my suggestions for the general App configuration, in no specific order:

- The new main battery SOC text color (orange) on the Info fragmet is hard to read, especially for people with visual impairments (color blindness) despite the new size. The IDE also warns about the contrast on this. I suggest reverting to plain white, which has proven to be good on both the green and the grey background. The shadow is nice & can be kept.
- The charge time estimations boxes need to be reverted to their original size and paddings: the right box (ETR full) is higher now than the left one (90px instead of 76px), shifting the icon to below the background gradient. Also the larger text size does not allow for cars with both sufficient range & SOC displays, like for example the Twizy, and the double padding (start&end) now causes even a standard single SOC time to break into two lines. The padding should be only "paddingRight", as it's meant to leave space for the icons, and the text size needs to be 24px. Also, the text gravity needs to be centered vertically + right, to accomodate for different line counts… or, IOW, simply fully revert both boxes to their previous attributes. I think you don't need them anyway now for the Smart EQ, do you?
- Two decimals for the 12V display seems a bit over the top…? Especially when taking into account most users won't even bother to calibrate their 12V readings…
- The date format option is not a plugin, it's a locale config. We added the other regional prefs options (tyre pressure & temperatures) to the Car fragment's menu, so that may be an option. Or you can move all three into the global options fragment, but then under a separate label, not as "Plugins". I'm also not sure if we actually need to have this as a user option. Why not use the Android's system locale settings for this? Btw, I'd like to see this for the pressure & temperature units as well, maybe you can give that a try while you're at it?
- The plugin & firmware update controls are currently clearly a pure developer & beta tester feature. Normal users should have the auto update enabled and only install the `main` releases. And the plugin controls are currently fixed & tailored for developers only. So you should clearly state their purpose in the info text below these, so normal users don't accidentally enable them and run into problems trying to use them.
- If you actually deem some of the current Smart EQ "plugin" functions as usable by normal users (?), it's best to separate them and add them as a general menu/fragment when a Smart vehicly type is detected.

Regards,
Michael

**Comment by zorgms** [comment]
I could certainly undo some changes and adjust others, but there are too many things that have been changed in the last three months. A note in between would have helped. Now I'm withdrawing my change request with regard to #177 , as the new UI is much better positioned and my adjustments would have to be implemented there first, so it's simply no longer worth adjusting anything.

Regards,
Michael

**Comment by developerfromjokela** [comment]
> I could certainly undo some changes and adjust others, but there are too many things that have been changed in the last three months. A note in between would have helped. Now I'm withdrawing my change request with regard to #177 , as the new UI is much better positioned and my adjustments would have to be implemented there first, so it's simply no longer worth adjusting anything.
> 
> Regards, Michael

You're welcome to do image files for smart EQ, they're still missing from new release.

It needs doors, charging port, cable plugged in, etc. There's still work to be done for each model :)

**Pull request closed without merging**
