### PR TITLE
Support for Energica motorcycles

### PR DESCRIPTION
**Pull request by matthieu-labas**
Added images adn support for Energica models SS9, Ribelle, Ego and Experia.
Maybe the images are a bit big? I can reduce the size if needed (but they look good ;-)).

### CODE REVIEW

**Comment by dexterbg** [comment]
Yes, the images are too big.
See https://github.com/openvehicles/Open-Vehicle-Android/pull/170#issuecomment-2266428291

You'll be surprised how much can be gained without compromising too much on image quality. Just give the tool a try.

Regards,
Michael

**Comment by matthieu-labas** [comment]
Awesome tool! I reduced the images sizes too and renamed them to better suit the `car_<name>_<color>` pattern.

**Comment by dexterbg** [comment]
Time to prepare a new release I guess :-)
But there are some open Kotlin issues to fix before.

**Comment by dexterbg** [comment]
Kotlin build 4.6.1 including the Energica is in `latest`.

**Comment by matthieu-labas** [comment]
> Time to prepare a new release I guess :-) But there are some open Kotlin issues to fix before.

Oh, is there anything I can do about it?

**Comment by dexterbg** [comment]
Maybe, see crash reports here: https://github.com/openvehicles/Open-Vehicle-Android/pull/166

**Comment by matthieu-labas** [comment]
> Maybe, see crash reports here: #166

Well, I did run some tests on my version (with the Energica "car") and didn't find any exception, except for the Firebase and Google Map API keys, which are normal in dev environment I guess...

**Comment by dexterbg** [comment]
The builds I provide here under "latest" are done with the OVMS key, they should have no functional restrictions. Basically the same as gets published via Google Play.

**Pull request merged**
