### PR TITLE
Update app to target sdk 28

### PR DESCRIPTION
**Pull request by mbernier85**
Hi everyone, I'm a new Leaf owner, and just found out about your project.

I do Android for a living and wanted to give you a hand with this app on my free time.

So as a first try I decided to update your app to the near latest sdk, next step would be to move to api29, but this was a first step

let me know what you think.

### CODE REVIEW

**Comment by dexterbg** [comment]
Welcome Michael :-)

Please also register for the developer mailing list, that's our main communication channel.

Most annoying issues with the current App are a) TCP reconnect issues on Android 7 & up due to power management, b) package size due to all image sets included in the App package (should be addons). But all help on improving the App is greatly appreciated.

Regards,
Michael

**Comment by dexterbg** [comment]
Michael, when uploading this release to the Google Play Console, it tells me we will lose support for a substantial amount of users due to the App no longer supporting their API level. The console suggests to support API level 21, but minSdk is set to 21 already. Any idea what's going wrong here?

**Comment by dexterbg** [comment]
Solved: a number of users still are on API levels 16+, so I've lowered minSdk to 16.

**Comment by dexterbg** [comment]
Annoying side effect of the API level changes: the play store update killed all user configurations.

**Comment by mbernier85** [comment]
I don't think changing the api level is what caused the data loss, might be related to something else.

**Comment by dexterbg** [comment]
All other changes were minor, no data structure changes. SDK 28 also introduced a new SQLite file format with broken upgrade leading to crashes on a number of devices, see my post on the developer list.

**Pull request merged**
