### PR TITLE
car: Add BoltEV image

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by dexterbg** [comment]
Alex, this is missing at least two images & the corresponding code changes, and the image is quite large as well -- did you apply the optimizer?

Please follow the guide: https://github.com/openvehicles/Open-Vehicle-Android/wiki/Adding-Vehicle-Images

**Comment by kallisti5** [comment]
I updated the image with the optimizer applied.        Still looking for an overhead shot of the Bolt EV (though, I really don't use that screen very often to be honest... we could just keep using the generic picture)

**Comment by kallisti5** [comment]
https://hum2d.com/clipart/chevrolet-bolt-ev-2017/ yesh.  $25

**Comment by billatq** [comment]
These two images would probably be a good starting point:

chevy-bolt-main
chevy-bolt-overhead

**Comment by kallisti5** [comment]
Ok @dexterbg   I used @billatq 's images. Added some custom overlays for DCFC and AC charging.  I haven't tried to compile this, been ages since I tried Android development lol.

Hopefully all the edge cases are met?

**Comment by dexterbg** [comment]
As the "ol" main image was suspiciously large, I've just applied our recommended optimizer to both main images, quality 75%. No visible issues and quite some reduction.

car_boltev_summitwhite
ol_car_boltev_summitwhite

**Comment by kallisti5** [comment]
Both images applied to commit @dexterbg

**Comment by dexterbg** [comment]
Updated build is in [latest](https://github.com/openvehicles/Open-Vehicle-Android/tree/master/latest).

**Comment by kallisti5** [comment]
Ayeee! Not bad!  :-)

**Pull request merged**
