### PR TITLE
Display charging power

### PR DESCRIPTION
**Pull request by glynhudson**
- Display charging power (kW) when EV is charging
- Uses `car_charge_power_kw` if available, if not (as is the case with Nissan leaf), power is calculated by multiplying current and voltage.

A display of charging power help avoid the confusion I experienced due to confusing DC current with AC current https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/issues/149. Most EV drivers are most familiar with charging power in kW rather than battery voltage/ DC current. 

Location and font size open to discussion? 

screenshot_20180813-133924

### CODE REVIEW

**Comment by dexterbg** [comment]
This needs a little bit more work ;-)

1. Be aware the power levels are at the battery, not at the plug. So the power display does not take charge efficiency into account, the values may confuse users.
2. The charge current was never defined to be specifically the line current, it can be the battery current as well, depending on what is available on the vehicle bus.
3. In both cases, vehicles normally do not know the actual charge efficiency, so deriving line power levels from battery levels introduces a potentially large error. On the Twizy I show both the hard fact (battery) and the estimation of the line level, but the estimation is up to 20% off the real level.
4. Please do not confuse units. Power = kW, energy = kWh.

**Comment by glynhudson** [comment]
>Be aware the power levels are at the battery, not at the plug. So the power display does not take charge efficiency into account, the values may confuse users.

I'm aware of this, however in my opinion it's the power actually charging the battery is what is of interest to a user. Since OVMS is already showing the pack voltage and the input current, why not also show the product input power? This is what is displaed on the dashboard of most EV's, rather than the outlet power. Since the charging efficiency is impossible for the car to calculate since there will be some losses in the wall box / EVSE unit or DC rapid charger that are not visible to the EV / OVMS. Most EV's have charging efficiency > 90% but this varies with charging power. 

>The charge current was never defined to be specifically the line current, it can be the battery current as well, depending on what is available on the vehicle bus.

How best can we handle this? I believe on a Nissan leaf (the EV I'm testing with) the `car_charge_current` is the battery current e.g in my screenshot above when the line current is 6A and the `car_charge_current`  (battery current) is 3A. 

Are you saying that on other EV's `car_charge_current` could return the line current making my power calculation incorrect when line current is multiped by battery pack voltage?

>In both cases, vehicles normally do not know the actual charge efficiency, so deriving line power levels from battery levels introduces a potentially large error. On the Twizy I show both the hard fact (battery) and the estimation of the line level, but the estimation is up to 20% off the real level.

Yes, the charging efficiency is impossible for the EV to calculate. It varies with charging current. Here's a graph of leaf charging efficiency. IMO I think we should just display what we can measure accurately
screenshot 2018-08-15 at 00 41 39
. 
>Please do not confuse units. Power = kW, energy = kWh.

I'm not, this PR is to display charging Power (in kW). I never mentioned energy! 

Displaying kWh of a charge session is a good idea, but would obviously require knowledge of the charging time elapsed. Does OVSM keep a track of this? Adding a display of energy delivered in kWh would be a really nice addition. Would you be open to this? In a separate PR?

**Comment by dexterbg** [comment]
> Do you think any further UI elements are needed to communicate to the user that this is battery power rather than line power?

Yes. I think it's misleading that it's shown on the plug (the current as well…). It should be displayed somehow as the battery input. Maybe it could be OK on the plug if it also displayed an estimation of the line power, e.g. "1.2 kW ← ~1.5 kW", but that could be overloading the page.

> How can I get in touch with Tom?

Best on the developer mailing list, as other Leaf developers have joined lately.

**Comment by glynhudson** [comment]
>Yes. I think it's misleading that it's shown on the plug (the current as well…). It should be displayed somehow as the battery input

How about moving the battery power display to be just above the battery e.g. 

untitled

Note: this image is just a messy mockup in gimp!

**Comment by dexterbg** [comment]
Glyn, as we added the actual charger input power to the metrics and "S" message a while ago, this could now be implemented without ambiguity and App-side calculations. The latest commits contain this, following your original suggestion and extending that by displaying the charge losses if both power levels are known.

**Comment by glynhudson** [comment]
Fantastic! I've just got the latest update on my app, this is perfect. Nice work 👍

**Pull request closed without merging**
