### PR TITLE
Lock icon redesign + you guessed it, more compression

### PR DESCRIPTION
**Pull request by dalathegreat**
- Lock icon redesign to make it appear more like a lock with keyhole. 
- 157kb saved from compressing icon images

image

Side question, the blotches originate from the Tesla Roadster seats right? So why are we using this overlay for all other cars?

### CODE REVIEW

**Comment by dexterbg** [comment]
Historical reasons ;-)

But team Zoe already added "_clean" variants, so I suggest you apply your change to these too, and I'll change them to become the default.

**Comment by dexterbg** [comment]
I just see the "_clean" variants look pretty bad, because they are lacking a smooth edge transition to transparency. Can you take care of making them look good?

**Comment by dalathegreat** [comment]
Done
image

**Comment by dexterbg** [comment]
Logic is updated… seeing the lock & valet icons side by side now I also see a color difference, besides the hard edges.

**Pull request merged**
