### PR TITLE
bug of update of database to version 5

### PR DESCRIPTION
**Pull request by anhr**

### CODE REVIEW

**Comment by dexterbg** [comment]
Hi Andrej,

your pull request seems to lack some change, it only contains a new exception thrown (?)

Instead of throwing an exception at that point, which crashes the App just the same way as without that check, there should be a better way. Also, I don't get how db==null could happen there, can you elaborate a bit on this?

Thanks!
Michael

**Comment by anhr** [comment]
Hi Michael,

Thanks for responce. I am beginner in GitHub and this is my first pull. Now I see, someone read my pull and I can continue my researching of your code if you interested.
About one year ago I have downloaded a ZIP of Open-Vehicle-Android project into my local machine I have begun my work for it. Now I want make my contribute into Open-Vehicle-Android project. I have made a clone in desktop of your last version. Now I want merge my work with your last version, but your last version is failed to run on my Android device. I have detected, your version is crashed on my device because db == null. Your version was lauched successfuly on my Android device after my changes. I don't get how db==null could happen there also. Currently my database was updated to version 5 and I can not repeat this problem. I can investigate it if you want. I will glad, if you explain me how to return to database verion 1 for continuing of my researching.

About my work. I have added the 24 hour logged path of the vehicle into Google map.  User can see a track of his vehicle for last 24 hours. Also he can see the speed and other values for each location of the car for last 24 hours. Are you interested in my work?

Many bugs was fixed also.

Thanks!
Andrej

**Comment by anhr** [comment]
See my new "bug of update of database to version 5" Commit on Apr 14, 2015

**Comment by dexterbg** [comment]
Hi Andrej,

bug and solution are now clear, thanks! Your solution of an add...() with explicit db parameter is good. A writable db is delivered to onUpdate() and needs to be used within the update procedure. Another solution would be to do "this.db = db;" in onUpdate(), but your solution is better, I'll merge that later on.

For your GPS track display, that would be really neat and has already been asked for by other users. Did you base your work on my GPSLogData storage class? That would be perfect as that's intended to be shared between the power history display and the track display. The track display also can use the power/energy info to create a nice energy heatmap like explained in the GPS visualization howto, and the GPSLogData class already contains load/save functions to be able to store some tracks for later comparisons.

Thanks & regards,
Michael

**Comment by dexterbg** [comment]
Forgot: there is no real db downgrade procedure, you can only set the version tag to let the onUpgrade() be run again. To do so, set the SCHEMA_VERSION to the lower version, launch once, then raise the version again and launch again. The onUpgrade() should be called again and needs to be able to handle already existing upgrade structs.

**Comment by dexterbg** [comment]
Andrej, would you mind joining the OVMS developer mailing list?
http://lists.teslaclub.hk/mailman/listinfo/ovmsdev
No noise there, just developers ;)

**Comment by anhr** [comment]
I have joined. Thanks.


Вторник, 14 апреля 2015, 10:14 -07:00 от Michael Balzer <notifications@github.com>:

**Comment by anhr** [comment]
I did not develop the server side of the OVMS project. Another guy - Lee Howard lee.howard@mainpine.com wrote it. Attached is the patch for the perl code which is made to the server to support the logged path.

We have added new command:
Please refer to pages 24 through 30 of OVMS_Protocol.pdf where it discusses 
"Commands and Expected Responses". To retrieve 24-hour log data for a 
vehicle it is similar to "32 - Request historical data records". The 
documentation for "Retrieve 24-hour log data" should read:
---------------------------
33 -­ Retrieve 24-hour log data
Command parameters are:
* code (the record type to retrieve)
Response is a sequence of individual messages with each message containing
the following parameters:
* response record number
* maximum number of response records
* data code type
* data record timestamp
* data record value
---------------------------
The "code" can be any of those described on pages 10 through 23, 
however, for GPS location you will want to use code "L" as described on 
page 21.
On the OVMS "Location" screen I would like there to be an option appear 
under "Options" that says "Turn Logged Path ON". When it is pressed it 
should change to "Turn Logged Path OFF". By default, the logged path is 
not displayed until the user presses "Turn Logged Path ON". If the user 
then presses "Turn Logged Path OFF" it should return to the default of 
only displaying the current location.
Понедельник, 13 апреля 2015, 23:54 -07:00 от Michael Balzer <notifications@github.com>:

**Comment by markwj** [comment]
If someone wants to set this patch up as a pull request for the main ovms_server.pl, I'd be happy to bring it in.

**Comment by dexterbg** [comment]
That's a useful server extension. I'll have a look if we can extend the L records by the power data, so we can produce some heatmap from those records as well.

For the options menu, please have a look at my latest changes -- I replaced those text switching menus by standard checkbox items.

**Comment by anhr** [comment]
Hello,

Do you saw:
I have removed some strings from resources #54
https://github.com/openvehicles/Open-Vehicle-Android/pull/54 My location button
https://github.com/anhr/Open-Vehicle-Android/commit/6a99d3fc73044c20dc6296450e97194c25300776

Can you comment this?

Andrej

Понедельник, 13 апреля 2015, 23:54 -07:00 от Michael Balzer <notifications@github.com>:

**Pull request merged**
